  version: '3.11'

  services:
    localstack:
      image: localstack/localstack-pro:latest
      container_name: localstack_appsync
      ports:
        - 4566:4566
      environment:
        - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
